### ISSUE TITLE
64bit version ? :) thx

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-cpp-markdown#1]
i'm not a good compiler Xcode :)

**Comment by miyako** [comment]
is the plugin useful?

please try [2.0.3](https://github.com/miyako/4d-plugin-cpp-markdown/releases/tag/2.0.3)

**Comment by olivierfaure** [comment]
Hi,

2.0.1 works well in Catalina, except it asks 4x for security in first 4 launches of the base, after it's ok.

After test, it's incomplete because tables are not converted in HTML :( like some line command "markdown-to-html"

I found one which works well in line command (with tables…) but (so sad) not inside 4D, i explain :

1. npm install markdown-to-html -g
2. "markdown /Users/olivier/WiseDyn/Web/noma/trainings/linux/linuxGuidePractice.md" (exemple)
	and terminal display good result :)

In 4D, the same command just output an error : env: node: No such file or directory

even if i put the complete path of the command and complete path of the file :( if you have an idea…

i tried too to pass the path in Environnement variable with 4D without success.

thx anyway :)

Olivier Faure
Responsable Développements



41 rue Yves Montand, 34080 Montpellier
www.noma.fr
olivier@noma.fr
04 67 75 44 62

**Comment by miyako** [comment]
different libraries support .``md`` to different degrees.

https://github.com/miyako/4d-plugin-discount

is another example.

**Comment by miyako** [comment]
for the record, after I posted 2.0.1, I updated my comment with 2.0.3.

2.0.1 is notarised but not stapled, meaning, if you run on a Mac disconnected from the network, 
it will not be able to check if the app is notarised by Apple.

maybe that explains the 4 dialogs.

maybe you won't have that issue with 2.0.3.

**Comment by miyako** [comment]
discount supports tables 

```
$in:="aaa | bbbb\r\n-----|------\r\nhello|sailor"
$err:=Markdown ($in;$out)
```
